In [54]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df = pd.read_csv("IPL.csv")
df.head()

Toss Winner Vs Match Winner

In [ ]:
toss_winner = df['toss_winner'].value_counts()
toss_winner
sns.barplot(y = toss_winner.index,x = toss_winner.values)
plt.title("Toss Winners")
plt.xlabel("TEAM Name")
plt.ylabel("Toss")

In [ ]:
match_winner = df['match_winner'].value_counts()
sns.barplot(y = match_winner.index, x = match_winner.values)
plt.title("Match Winners")
plt.xlabel("Matches")
plt.ylabel("Team")

In [ ]:
df.head()
identify = df[df['toss_winner']==df['match_winner']].count()
team_who_won_toss_also_won_match = identify['match_winner']
team_who_won_toss_also_won_match
percentage = (team_who_won_toss_also_won_match *100 )/ df.shape[0]
percentage
print(f"There are {percentage}% chance team who won the toss also won the match.")

In [ ]:
df.head()
avg_score_by_venue = df.groupby('venue')['first_ings_score'].mean()
approximate_avg_score = avg_score_by_venue.values.round()
sns.barplot(y = avg_score_by_venue.index,x = approximate_avg_score)
plt.title("Average First Ining Score")
plt.xlabel("Score")
plt.ylabel("Venue")

In [ ]:
df.head()
avg_score_by_venue = df.groupby('venue')['second_ings_score'].mean()
approximate_avg_score = avg_score_by_venue.values.round()
sns.barplot(y = avg_score_by_venue.index,x = approximate_avg_score)
plt.title("Average Second Ining Score")
plt.xlabel("Score")
plt.ylabel("Venue")

In [ ]:
df.head()
won_by = df['won_by'].value_counts()
sns.countplot(won_by)

In [ ]:
df.head()
top_scorer = df.groupby('top_scorer')['highscore'].sum().sort_values(ascending=False).head(5)
sns.barplot(y = top_scorer.index,x = top_scorer.values)
plt.title("Top 5 Player score")
plt.xlabel("Runs")
plt.ylabel("Player Name")

In [ ]:
playerofthematch = df['player_of_the_match'].value_counts().sort_values(ascending=False).head()
playerofthematch

In [22]:
df.head()
toss_decision = df['toss_decision'].value_counts()
toss_percentage_field = (toss_decision['Field'] * 100) / df.shape[0]
toss_percentage_bat = (toss_decision['Bat'] * 100) / df.shape[0]
toss_percentage_bat
toss_percentage_field

np.float64(79.72972972972973)

In [58]:
df.head()
chase = df[df['won_by']=='Wickets']
chase.head()
highest_chase = chase.loc[chase['first_ings_score'].idxmax()]
highest_chase

match_id                                       7
date                               March 31,2022
venue                  Brabourne Stadium, Mumbai
team1                                    Chennai
team2                                    Lucknow
stage                                      Group
toss_winner                              Lucknow
toss_decision                              Field
first_ings_score                             210
first_ings_wkts                                7
second_ings_score                            211
second_ings_wkts                               4
match_winner                             Lucknow
won_by                                   Wickets
margin                                         6
player_of_the_match                   Evin Lewis
top_scorer                       Quinton de Kock
highscore                                     61
best_bowling                        Ravi Bishnoi
best_bowling_figure                        2--24
Name: 6, dtype: object

In [59]:
top_chases = chase.sort_values(by='first_ings_score',ascending=False).head()
top_chases

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
6,7,"March 31,2022","Brabourne Stadium, Mumbai",Chennai,Lucknow,Group,Lucknow,Field,210,7,211,4,Lucknow,Wickets,6,Evin Lewis,Quinton de Kock,61,Ravi Bishnoi,2--24
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
39,40,"April 27,2022","Wankhede Stadium, Mumbai",Gujarat,Hyderabad,Group,Gujarat,Field,195,6,199,5,Gujarat,Wickets,5,Umran Malik,W. Saha,68,Umran Malik,5--25
51,52,"May 7,2022","Wankhede Stadium, Mumbai",Punjab,Rajasthan,Group,Punjab,Bat,189,5,190,4,Rajasthan,Wickets,6,Yashasvi Jaiswal,Yashasvi Jaiswal,68,Yuzvendra Chahal,3--28
15,16,"April 8,2022","Brabourne Stadium, Mumbai",Gujarat,Punjab,Group,Gujarat,Field,189,9,190,4,Gujarat,Wickets,6,Shubman Gill,Shubman Gill,96,Rashid Khan,3--22

In [63]:
top_chases['loser_team'] = np.where(top_chases['match_winner']==top_chases['team1'],top_chases['team2'],top_chases['team1'])
top_chases

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,loser_team
6,7,"March 31,2022","Brabourne Stadium, Mumbai",Chennai,Lucknow,Group,Lucknow,Field,210,7,...,4,Lucknow,Wickets,6,Evin Lewis,Quinton de Kock,61,Ravi Bishnoi,2--24,Chennai
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,...,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59,Banglore
39,40,"April 27,2022","Wankhede Stadium, Mumbai",Gujarat,Hyderabad,Group,Gujarat,Field,195,6,...,5,Gujarat,Wickets,5,Umran Malik,W. Saha,68,Umran Malik,5--25,Hyderabad
51,52,"May 7,2022","Wankhede Stadium, Mumbai",Punjab,Rajasthan,Group,Punjab,Bat,189,5,...,4,Rajasthan,Wickets,6,Yashasvi Jaiswal,Yashasvi Jaiswal,68,Yuzvendra Chahal,3--28,Punjab
15,16,"April 8,2022","Brabourne Stadium, Mumbai",Gujarat,Punjab,Group,Gujarat,Field,189,9,...,4,Gujarat,Wickets,6,Shubman Gill,Shubman Gill,96,Rashid Khan,3--22,Punjab

In [69]:
df.head()
df[['Wicket','Run']] = df['best_bowling_figure'].str.split('--',expand=True)
df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,Wicket,Run
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,...,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20,3,20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,...,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18,3,18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,...,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59,2,59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,...,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25,3,25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,...,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22,3,22

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     str
 2   venue                74 non-null     str
 3   team1                74 non-null     str
 4   team2                74 non-null     str
 5   stage                74 non-null     str
 6   toss_winner          74 non-null     str
 7   toss_decision        74 non-null     str
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     str
 13  won_by               74 non-null     str
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     str
 16  top_scorer           74 non-null     str
 17  highscore            74 non-null     int64
 18  best_bowling         74 non-null     str
 19  best_bowling_figure  74 non-null     str
 20  Wicket               74 non-null     str
 21  Run                  74 non-null     str
dtypes: int64(7), str(15)
memory usage: 22.4 KB

In [72]:
df['Wicket'] = df['Wicket'].astype(int)
df['Run'] = df['Run'].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     str
 2   venue                74 non-null     str
 3   team1                74 non-null     str
 4   team2                74 non-null     str
 5   stage                74 non-null     str
 6   toss_winner          74 non-null     str
 7   toss_decision        74 non-null     str
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     str
 13  won_by               74 non-null     str
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     str
 16  top_scorer           74 non-null     str
 17  highscore            74 non-null     int64
 18  best_bowling         74 non-null     str
 19  best_bowling_figure  74 non-null     str
 20  Wicket               74 non-null     int64
 21  Run                  74 non-null     int64
dtypes: int64(9), str(13)
memory usage: 22.2 KB

In [75]:
highest_wicket_taker = df.groupby('best_bowling')['Wicket'].sum()
highest_wicket_taker.sort_values(ascending=False).head()

best_bowling
Yuzvendra Chahal    17
Jasprit Bumrah      11
Kuldeep Yadav       11
Rashid Khan         11
Josh Hazlewood      10
Name: Wicket, dtype: int64

In [83]:
run_canside = df.groupby('best_bowling')['Run'].sum()
run_canside.sort_values(ascending=False)

best_bowling
Yuzvendra Chahal      146
Rashid Khan           102
Josh Hazlewood         96
Kagiso Rabada          94
T Natarajan            81
Avesh Khan             73
Kuldeep Yadav          67
Maheesh Theekshana     60
Mohammed Siraj         59
Harshal Patel          57
Umran Malik            53
Jasprit Bumrah         52
Lockie Ferguson        51
Ravi Bishnoi           46
Mukesh Choudhary       46
Tim Southee            46
Daniel Sams            46
Prasidh Krishna        44
Mohammed Shami         44
Dwayne Bravo           43
Wanindu Hasaranga      38
Shardul Takur          36
Mohsin Khan            36
Hardik Pandya          31
Odean Smith            30
Khaleel Ahmed          30
Andre Russell          27
Harpreet Brar          26
Murugan Ashwin         25
Rahul Chahar           25
Rilley Meredith        24
Chetan Sakariya        23
Umesh Yadav            23
Washington Sundar      21
Prashant Solanki       20
Ramandeep Singh        20
Kuldeep Sen            20
Krunal Pandya          19
Pradeep Sangwan        19
Trent Boult            18
Moeen Ali              13
Axar Patel             10
Name: Run, dtype: int64

In [ ]:
#Assuming that each bowler bowl atleast 20 overs

match_winner
Gujarat      12
Rajasthan    10
Banglore      9
Lucknow       9
Delhi         7
Punjab        7
Kolkata       6
Hyderabad     6
Chennai       4
Mumbai        4
Name: count, dtype: int64

In [82]:
df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,Wicket,Run
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,...,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20,3,20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,...,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18,3,18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,...,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59,2,59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,...,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25,3,25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,...,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22,3,22