In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
actual_df = pd.read_csv("CWC2023.csv")
actual_df.head()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,No Balls B,Penalty B,Extras B,Wining Team,Margin,Man of the Match,Umpire 1,Umpire 2,TV Umpire,Match Refree
0,1,05-10-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,England,NewZealand,NewZealand,Field,282,...,0,0,6,NewZealand,9 Wickets,Rachin Ravindra,Kumar Dharmasena,Nitin Menon,Paul Wilson,Javagal Srinath
1,2,06-10-2023,2:00 PM,Hyderabad,Eden Gardens,Pakistan,Netherlands,Netherlands,Field,286,...,1,0,9,Pakistan,81 Runs,Saud Shakeel,Adrian Holdstock,Chris Brown,Rod Tucker,Jeff Crowe
2,3,07-10-2023,2:00 PM,Dharamshala,HPCA Stadium,Afghanistan,Bangladesh,Bangladesh,Field,156,...,0,0,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz,Joel Wilson,Kumar Dharmasena,Ahsan Raza,Andy Pycroft
3,4,07-10-2023,2:00 PM,Delhi,Arun Jaitley Stadium,South Africa,Sri Lanka,Sri Lanka,Field,428,...,1,0,23,South Africa,102 Runs,Aiden Markram,Richard Illingworth,Sharfuddoula,Michael Gough,Javagal Srinath
4,5,08-10-2023,2:00 PM,Chennai,M. A. Chidambaram Stadium,Australia,India,Australia,Bat,199,...,0,0,12,India,6 wickets,KL Rahul,Chris Gaffaney,Richard Kettleborough,Chris Brown,Richie Richardson

In [71]:
df = actual_df.copy()
df.head()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,No Balls B,Penalty B,Extras B,Wining Team,Margin,Man of the Match,Umpire 1,Umpire 2,TV Umpire,Match Refree
0,1,05-10-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,England,NewZealand,NewZealand,Field,282,...,0,0,6,NewZealand,9 Wickets,Rachin Ravindra,Kumar Dharmasena,Nitin Menon,Paul Wilson,Javagal Srinath
1,2,06-10-2023,2:00 PM,Hyderabad,Eden Gardens,Pakistan,Netherlands,Netherlands,Field,286,...,1,0,9,Pakistan,81 Runs,Saud Shakeel,Adrian Holdstock,Chris Brown,Rod Tucker,Jeff Crowe
2,3,07-10-2023,2:00 PM,Dharamshala,HPCA Stadium,Afghanistan,Bangladesh,Bangladesh,Field,156,...,0,0,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz,Joel Wilson,Kumar Dharmasena,Ahsan Raza,Andy Pycroft
3,4,07-10-2023,2:00 PM,Delhi,Arun Jaitley Stadium,South Africa,Sri Lanka,Sri Lanka,Field,428,...,1,0,23,South Africa,102 Runs,Aiden Markram,Richard Illingworth,Sharfuddoula,Michael Gough,Javagal Srinath
4,5,08-10-2023,2:00 PM,Chennai,M. A. Chidambaram Stadium,Australia,India,Australia,Bat,199,...,0,0,12,India,6 wickets,KL Rahul,Chris Gaffaney,Richard Kettleborough,Chris Brown,Richie Richardson

In [72]:
df['venue'] =  df['Stadium'] + ", "+ df['City'] 
df.head()

,Match ID,Match Date,Match Time,City,Stadium,Team A,Team B,Toss Winner,Toss Decision,Score A,...,Penalty B,Extras B,Wining Team,Margin,Man of the Match,Umpire 1,Umpire 2,TV Umpire,Match Refree,venue
0,1,05-10-2023,2:00 PM,Ahmedabad,Narendra Modi Stadium,England,NewZealand,NewZealand,Field,282,...,0,6,NewZealand,9 Wickets,Rachin Ravindra,Kumar Dharmasena,Nitin Menon,Paul Wilson,Javagal Srinath,"Narendra Modi Stadium, Ahmedabad"
1,2,06-10-2023,2:00 PM,Hyderabad,Eden Gardens,Pakistan,Netherlands,Netherlands,Field,286,...,0,9,Pakistan,81 Runs,Saud Shakeel,Adrian Holdstock,Chris Brown,Rod Tucker,Jeff Crowe,"Eden Gardens, Hyderabad"
2,3,07-10-2023,2:00 PM,Dharamshala,HPCA Stadium,Afghanistan,Bangladesh,Bangladesh,Field,156,...,0,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz,Joel Wilson,Kumar Dharmasena,Ahsan Raza,Andy Pycroft,"HPCA Stadium, Dharamshala"
3,4,07-10-2023,2:00 PM,Delhi,Arun Jaitley Stadium,South Africa,Sri Lanka,Sri Lanka,Field,428,...,0,23,South Africa,102 Runs,Aiden Markram,Richard Illingworth,Sharfuddoula,Michael Gough,Javagal Srinath,"Arun Jaitley Stadium, Delhi"
4,5,08-10-2023,2:00 PM,Chennai,M. A. Chidambaram Stadium,Australia,India,Australia,Bat,199,...,0,12,India,6 wickets,KL Rahul,Chris Gaffaney,Richard Kettleborough,Chris Brown,Richie Richardson,"M. A. Chidambaram Stadium, Chennai"

Dropping Unnecessary Columns

In [73]:
clean_df = df.drop(columns=['Match ID','Match Date','Match Time','City','Stadium','Umpire 1','Umpire 2','TV Umpire','Match Refree'])
clean_df.head()

,Team A,Team B,Toss Winner,Toss Decision,Score A,Wickets A,Overs Played A,Maiden Overs A,4s A,6s A,...,Leg Byes B,Byes B,Wides B,No Balls B,Penalty B,Extras B,Wining Team,Margin,Man of the Match,venue
0,England,NewZealand,NewZealand,Field,282,9,50.0,2,21,6,...,0,0,6,0,0,6,NewZealand,9 Wickets,Rachin Ravindra,"Narendra Modi Stadium, Ahmedabad"
1,Pakistan,Netherlands,Netherlands,Field,286,10,49.0,1,33,3,...,0,0,8,1,0,9,Pakistan,81 Runs,Saud Shakeel,"Eden Gardens, Hyderabad"
2,Afghanistan,Bangladesh,Bangladesh,Field,156,10,37.2,1,15,2,...,0,0,8,0,0,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz,"HPCA Stadium, Dharamshala"
3,South Africa,Sri Lanka,Sri Lanka,Field,428,5,50.0,1,45,14,...,1,0,21,1,0,23,South Africa,102 Runs,Aiden Markram,"Arun Jaitley Stadium, Delhi"
4,Australia,India,Australia,Bat,199,10,49.3,1,16,2,...,6,0,6,0,0,12,India,6 wickets,KL Rahul,"M. A. Chidambaram Stadium, Chennai"

In [74]:
clean_df.shape

(48, 36)

Fixing the Run rate B

In [75]:
clean_df['Runrate B'] = clean_df['Runrate B'].str.replace(',','.').astype(float)
clean_df['Runrate B'].dtype

dtype('float64')

In [76]:
clean_df.select_dtypes(exclude=np.number).columns.tolist()

['Team A',
 'Team B',
 'Toss Winner',
 'Toss Decision',
 'Wining Team',
 'Margin',
 'Man of the Match',
 'venue']

In [77]:
clean_df.head()

,Team A,Team B,Toss Winner,Toss Decision,Score A,Wickets A,Overs Played A,Maiden Overs A,4s A,6s A,...,Leg Byes B,Byes B,Wides B,No Balls B,Penalty B,Extras B,Wining Team,Margin,Man of the Match,venue
0,England,NewZealand,NewZealand,Field,282,9,50.0,2,21,6,...,0,0,6,0,0,6,NewZealand,9 Wickets,Rachin Ravindra,"Narendra Modi Stadium, Ahmedabad"
1,Pakistan,Netherlands,Netherlands,Field,286,10,49.0,1,33,3,...,0,0,8,1,0,9,Pakistan,81 Runs,Saud Shakeel,"Eden Gardens, Hyderabad"
2,Afghanistan,Bangladesh,Bangladesh,Field,156,10,37.2,1,15,2,...,0,0,8,0,0,8,Bangladesh,6 Wickets,Mehidy Hasan Miraz,"HPCA Stadium, Dharamshala"
3,South Africa,Sri Lanka,Sri Lanka,Field,428,5,50.0,1,45,14,...,1,0,21,1,0,23,South Africa,102 Runs,Aiden Markram,"Arun Jaitley Stadium, Delhi"
4,Australia,India,Australia,Bat,199,10,49.3,1,16,2,...,6,0,6,0,0,12,India,6 wickets,KL Rahul,"M. A. Chidambaram Stadium, Chennai"

Now Doing One Hot Encoding for venue

In [78]:
venue_encoded = pd.get_dummies(clean_df['venue'],drop_first=True)

In [79]:
clean_df = pd.concat([clean_df,venue_encoded],axis=1)
clean_df.head()

,Team A,Team B,Toss Winner,Toss Decision,Score A,Wickets A,Overs Played A,Maiden Overs A,4s A,6s A,...,"BRSABV Ekana Cricket Stadium, Lucknow","Eden Gardens, Hyderabad","Eden Gardens, Kolkata","HPCA Stadium, Dharamshala","M. A. Chidambaram Stadium, Chennai","M. Chinnaswamy Stadium, Bangalore","Maharashtra Cricket Association Stadium, Pune","Narendra Modi Stadium, Ahmedabad","Rajiv Gandhi International Stadium, Hyderabad","Wankhede Stadium, Mumbai"
0,England,NewZealand,NewZealand,Field,282,9,50.0,2,21,6,...,False,False,False,False,False,False,False,True,False,False
1,Pakistan,Netherlands,Netherlands,Field,286,10,49.0,1,33,3,...,False,True,False,False,False,False,False,False,False,False
2,Afghanistan,Bangladesh,Bangladesh,Field,156,10,37.2,1,15,2,...,False,False,False,True,False,False,False,False,False,False
3,South Africa,Sri Lanka,Sri Lanka,Field,428,5,50.0,1,45,14,...,False,False,False,False,False,False,False,False,False,False
4,Australia,India,Australia,Bat,199,10,49.3,1,16,2,...,False,False,False,False,True,False,False,False,False,False

In [80]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 46 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Team A                                         48 non-null     str
 1   Team B                                         48 non-null     str
 2   Toss Winner                                    48 non-null     str
 3   Toss Decision                                  48 non-null     str
 4   Score A                                        48 non-null     int64
 5   Wickets A                                      48 non-null     int64
 6   Overs Played A                                 48 non-null     float64
 7   Maiden Overs A                                 48 non-null     int64
 8   4s A                                           48 non-null     int64
 9   6s A                                           48 non-null     int64
 10  Boundaries A                                   48 non-null     int64
 11  Runrate A                                      48 non-null     float64
 12  Leg Byes A                                     48 non-null     int64
 13  Byes A                                         48 non-null     int64
 14  Wides A                                        48 non-null     int64
 15  No Balls A                                     48 non-null     int64
 16  Penalty A                                      48 non-null     int64
 17  Extras A                                       48 non-null     int64
 18  Score B                                        48 non-null     int64
 19  Wickets B                                      48 non-null     int64
 20  Overs Played B                                 48 non-null     float64
 21  Maiden Overs B                                 48 non-null     int64
 22  4s B                                           48 non-null     int64
 23  6s B                                           48 non-null     int64
 24  Boundaries B                                   48 non-null     int64
 25  Runrate B                                      48 non-null     float64
 26  Leg Byes B                                     48 non-null     int64
 27  Byes B                                         48 non-null     int64
 28  Wides B                                        48 non-null     int64
 29  No Balls B                                     48 non-null     int64
 30  Penalty B                                      48 non-null     int64
 31  Extras B                                       48 non-null     int64
 32  Wining Team                                    48 non-null     str
 33  Margin                                         48 non-null     str
 34  Man of the Match                               48 non-null     str
 35  venue                                          48 non-null     str
 36  BRSABV Ekana Cricket Stadium, Lucknow          48 non-null     bool
 37  Eden Gardens, Hyderabad                        48 non-null     bool
 38  Eden Gardens, Kolkata                          48 non-null     bool
 39  HPCA Stadium, Dharamshala                      48 non-null     bool
 40  M. A. Chidambaram Stadium, Chennai             48 non-null     bool
 41  M. Chinnaswamy Stadium, Bangalore              48 non-null     bool
 42  Maharashtra Cricket Association Stadium, Pune  48 non-null     bool
 43  Narendra Modi Stadium, Ahmedabad               48 non-null     bool
 44  Rajiv Gandhi International Stadium, Hyderabad  48 non-null     bool
 45  Wankhede Stadium, Mumbai                       48 non-null     bool
dtypes: bool(10), float64(4), int64(24), str(8)
memory usage: 18.5 KB

In [81]:
clean_df.columns

Index(['Team A', 'Team B', 'Toss Winner', 'Toss Decision', 'Score A',
       'Wickets A', 'Overs Played A', 'Maiden Overs A', '4s A', '6s A',
       'Boundaries A', 'Runrate A', 'Leg Byes A', 'Byes A', 'Wides A',
       'No Balls A', 'Penalty A', 'Extras A', 'Score B', 'Wickets B',
       'Overs Played B', 'Maiden Overs B', '4s B', '6s B', 'Boundaries B',
       'Runrate B', 'Leg Byes B', 'Byes B', 'Wides B', 'No Balls B',
       'Penalty B', 'Extras B', 'Wining Team', 'Margin', 'Man of the Match',
       'venue', 'BRSABV Ekana Cricket Stadium, Lucknow',
       'Eden Gardens, Hyderabad', 'Eden Gardens, Kolkata',
       'HPCA Stadium, Dharamshala', 'M. A. Chidambaram Stadium, Chennai',
       'M. Chinnaswamy Stadium, Bangalore',
       'Maharashtra Cricket Association Stadium, Pune',
       'Narendra Modi Stadium, Ahmedabad',
       'Rajiv Gandhi International Stadium, Hyderabad',
       'Wankhede Stadium, Mumbai'],
      dtype='str')

In [82]:
clean_df = clean_df.drop('venue',axis=1)

In [83]:
clean_df.columns

Index(['Team A', 'Team B', 'Toss Winner', 'Toss Decision', 'Score A',
       'Wickets A', 'Overs Played A', 'Maiden Overs A', '4s A', '6s A',
       'Boundaries A', 'Runrate A', 'Leg Byes A', 'Byes A', 'Wides A',
       'No Balls A', 'Penalty A', 'Extras A', 'Score B', 'Wickets B',
       'Overs Played B', 'Maiden Overs B', '4s B', '6s B', 'Boundaries B',
       'Runrate B', 'Leg Byes B', 'Byes B', 'Wides B', 'No Balls B',
       'Penalty B', 'Extras B', 'Wining Team', 'Margin', 'Man of the Match',
       'BRSABV Ekana Cricket Stadium, Lucknow', 'Eden Gardens, Hyderabad',
       'Eden Gardens, Kolkata', 'HPCA Stadium, Dharamshala',
       'M. A. Chidambaram Stadium, Chennai',
       'M. Chinnaswamy Stadium, Bangalore',
       'Maharashtra Cricket Association Stadium, Pune',
       'Narendra Modi Stadium, Ahmedabad',
       'Rajiv Gandhi International Stadium, Hyderabad',
       'Wankhede Stadium, Mumbai'],
      dtype='str')

Cleaning again

In [84]:
clean_df = clean_df.drop(columns=['Score A',
       'Wickets A', 'Overs Played A', 'Maiden Overs A', '4s A', '6s A',
       'Boundaries A', 'Runrate A', 'Leg Byes A', 'Byes A', 'Wides A',
       'No Balls A', 'Penalty A', 'Extras A', 'Score B', 'Wickets B',
       'Overs Played B', 'Maiden Overs B', '4s B', '6s B', 'Boundaries B',
       'Runrate B', 'Leg Byes B', 'Byes B', 'Wides B', 'No Balls B',
       'Penalty B', 'Extras B','Margin', 'Man of the Match'])
clean_df.head()

,Team A,Team B,Toss Winner,Toss Decision,Wining Team,"BRSABV Ekana Cricket Stadium, Lucknow","Eden Gardens, Hyderabad","Eden Gardens, Kolkata","HPCA Stadium, Dharamshala","M. A. Chidambaram Stadium, Chennai","M. Chinnaswamy Stadium, Bangalore","Maharashtra Cricket Association Stadium, Pune","Narendra Modi Stadium, Ahmedabad","Rajiv Gandhi International Stadium, Hyderabad","Wankhede Stadium, Mumbai"
0,England,NewZealand,NewZealand,Field,NewZealand,False,False,False,False,False,False,False,True,False,False
1,Pakistan,Netherlands,Netherlands,Field,Pakistan,False,True,False,False,False,False,False,False,False,False
2,Afghanistan,Bangladesh,Bangladesh,Field,Bangladesh,False,False,False,True,False,False,False,False,False,False
3,South Africa,Sri Lanka,Sri Lanka,Field,South Africa,False,False,False,False,False,False,False,False,False,False
4,Australia,India,Australia,Bat,India,False,False,False,False,True,False,False,False,False,False

In [85]:
clean_df.shape

(48, 15)

Encoding All categorical columns

In [86]:
clean_df = pd.get_dummies(clean_df, columns=[
    'Team A', 'Team B', 'Toss Winner', 'Toss Decision'
], drop_first=True)

In [87]:
clean_df.head()

,Wining Team,"BRSABV Ekana Cricket Stadium, Lucknow","Eden Gardens, Hyderabad","Eden Gardens, Kolkata","HPCA Stadium, Dharamshala","M. A. Chidambaram Stadium, Chennai","M. Chinnaswamy Stadium, Bangalore","Maharashtra Cricket Association Stadium, Pune","Narendra Modi Stadium, Ahmedabad","Rajiv Gandhi International Stadium, Hyderabad",...,Toss Winner_Australia,Toss Winner_Bangladesh,Toss Winner_England,Toss Winner_India,Toss Winner_Netherlands,Toss Winner_NewZealand,Toss Winner_Pakistan,Toss Winner_South Africa,Toss Winner_Sri Lanka,Toss Decision_Field
0,NewZealand,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,True
1,Pakistan,False,True,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,Bangladesh,False,False,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
3,South Africa,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,India,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

Defining X and Y

In [88]:
X = clean_df.drop('Wining Team',axis=1)
y = clean_df['Wining Team']

In [89]:
X.head()

,"BRSABV Ekana Cricket Stadium, Lucknow","Eden Gardens, Hyderabad","Eden Gardens, Kolkata","HPCA Stadium, Dharamshala","M. A. Chidambaram Stadium, Chennai","M. Chinnaswamy Stadium, Bangalore","Maharashtra Cricket Association Stadium, Pune","Narendra Modi Stadium, Ahmedabad","Rajiv Gandhi International Stadium, Hyderabad","Wankhede Stadium, Mumbai",...,Toss Winner_Australia,Toss Winner_Bangladesh,Toss Winner_England,Toss Winner_India,Toss Winner_Netherlands,Toss Winner_NewZealand,Toss Winner_Pakistan,Toss Winner_South Africa,Toss Winner_Sri Lanka,Toss Decision_Field
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [90]:
y.head()

0      NewZealand
1        Pakistan
2      Bangladesh
3    South Africa
4           India
Name: Wining Team, dtype: str

In [91]:
y.shape

(48,)

Installing scikit-learn

In [92]:
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\hrai2\AppData\Roaming\Python\Python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\hrai2\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\hrai2\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\hrai2\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\hrai2\AppData\Roaming\Python\Python313\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

Encoding Target

In [93]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

In [94]:
y

array([6, 7, 2, 8, 4, 6, 3, 7, 4, 8, 6, 4, 0, 1, 5, 6, 4, 1, 9, 8, 4, 0,
       8, 1, 9, 8, 1, 5, 4, 0, 7, 8, 4, 0, 7, 1, 4, 2, 1, 3, 6, 8, 1, 3,
       4, 4, 1, 1])

Train-Test split

In [95]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [96]:
X_train

,"BRSABV Ekana Cricket Stadium, Lucknow","Eden Gardens, Hyderabad","Eden Gardens, Kolkata","HPCA Stadium, Dharamshala","M. A. Chidambaram Stadium, Chennai","M. Chinnaswamy Stadium, Bangalore","Maharashtra Cricket Association Stadium, Pune","Narendra Modi Stadium, Ahmedabad","Rajiv Gandhi International Stadium, Hyderabad","Wankhede Stadium, Mumbai",...,Toss Winner_Australia,Toss Winner_Bangladesh,Toss Winner_England,Toss Winner_India,Toss Winner_Netherlands,Toss Winner_NewZealand,Toss Winner_Pakistan,Toss Winner_South Africa,Toss Winner_Sri Lanka,Toss Decision_Field
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
6,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
39,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
33,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
13,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
45,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
9,True,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
16,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
32,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
46,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
31,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,True
30,False,False,True,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
11,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,True
34,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
44,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
21,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
36,False,False,True,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
35,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,True
23,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
22,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
18,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
47,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True
20,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
42,False,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,True
14,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
28,True,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
38,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

Training the Model

In [97]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

Evaluate

In [98]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.5